Reservation_vols_version2_withEF/Models/Flight.cs
using System;
using System.Collections.Generic;

namespace Reservation_vols_version2_withEF.Models
{
    public partial class Flight
    {
        public Flight()
        {
            Tickets = new HashSet<Ticket>();
        }

        public Flight(DateTime datedeparture, DateTime datearrival, int airportdepartureid, int airportarrivalid)
        {
            this.AirportDepartureId = airportdepartureid;
            this.AirportArrivalId = airportarrivalid;
            this.DateDeparture = datedeparture;
            this.DateArrival = datearrival;
        }
        public int Flightid { get; set; }
        public bool? Isopen { get; set; }
        public DateTime DateDeparture { get; set; }
        public DateTime DateArrival { get; set; }
        public int AirportDepartureId { get; set; }
        public int AirportArrivalId { get; set; }

        public virtual Airport AirportArrival { get; set; } = null!;
        public virtual Airport AirportDeparture { get; set; } = null!;
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}

Reservation_vols_version2_withEF/Controllers/FlightsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Reservation_vols_version2_withEF.Models;
using Reservation_vols_version2_withEF.ViewModel;

namespace Reservation_vols_version2_withEF.Controllers
{
    public class FlightsController : Controller
    {
        private readonly Reservation_volsContext _context;

        public FlightsController(Reservation_volsContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index(string? DepartureAirport, string? ArrivalAirport)
        {
            //On préparer la requète, on va chercher uniquement les nom (select air.Name) pour les aéroports qui n'ont pas été supprimés (air.Isdeleted==false)
            var airports = from air in _context.Airports where air.Isdeleted==false select air.Name;

            IQueryable<Flight> reservation_volsContext = _context.Flights.Include(f => f.AirportArrival)
                    .Include(f => f.AirportDeparture);

            if (!string.IsNullOrEmpty(DepartureAirport))
            {
                reservation_volsContext = reservation_volsContext.Where(x => (string)x.AirportDeparture.Name == DepartureAirport);
            }

            if (!string.IsNullOrEmpty(ArrivalAirport))
            {
                reservation_volsContext = reservation_volsContext.Where(x => (string)x.AirportArrival.Name == ArrivalAirport);
            }


            var filteredIndexFlightsVM = new FilteredIndexFlightsVM
            {
                Airports = new SelectList(await airports.ToListAsync()),
                Flights = await reservation_volsContext.ToListAsync()
            };

            return View(filteredIndexFlightsVM);
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .Include(f => f.AirportArrival)
                .Include(f => f.AirportDeparture)
                .FirstOrDefaultAsync(m => m.Flightid == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            ViewData["AirportArrivalId"] = new SelectList(_context.Airports, "Airportid", "Name");
            ViewData["AirportDepartureId"] = new SelectList(_context.Airports, "Airportid", "Name");
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateDeparture,DateArrival,AirportDepartureId,AirportArrivalId")] CreatedFlightVM createdFlight)
        {
            Flight flight = new Flight(createdFlight.DateDeparture,createdFlight.DateArrival,createdFlight.AirportDepartureId, createdFlight.AirportArrivalId);
            flight.AirportArrival = await _context.Airports.FindAsync(createdFlight.AirportArrivalId);
            flight.AirportDeparture = await _context.Airports.FindAsync(createdFlight.AirportDepartureId);

            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AirportArrivalId"] = new SelectList(_context.Airports, "Airportid", "Name", flight.AirportArrivalId);
            ViewData["AirportDepartureId"] = new SelectList(_context.Airports, "Airportid", "Name", flight.AirportDepartureId);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            ViewData["AirportArrivalId"] = new SelectList(_context.Airports, "Airportid", "Airportid", flight.AirportArrivalId);
            ViewData["AirportDepartureId"] = new SelectList(_context.Airports, "Airportid", "Airportid", flight.AirportDepartureId);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Flightid,Isopen,DateDeparture,DateArrival,AirportDepartureId,AirportArrivalId")] Flight flight)
        {
            if (id != flight.Flightid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.Flightid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AirportArrivalId"] = new SelectList(_context.Airports, "Airportid", "Airportid", flight.AirportArrivalId);
            ViewData["AirportDepartureId"] = new SelectList(_context.Airports, "Airportid", "Airportid", flight.AirportDepartureId);
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .Include(f => f.AirportArrival)
                .Include(f => f.AirportDeparture)
                .FirstOrDefaultAsync(m => m.Flightid == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flights.FindAsync(id);
            _context.Flights.Remove(flight);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
            return _context.Flights.Any(e => e.Flightid == id);
        }
    }
}

Reservation_vols_version2_withEF/Views/Flights/Create.cshtml
@model Reservation_vols_version2_withEF.ViewModel.CreatedFlightVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateDeparture" class="control-label"></label>
                <input asp-for="DateDeparture" class="form-control" />
                <span asp-validation-for="DateDeparture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateArrival" class="control-label"></label>
                <input asp-for="DateArrival" class="form-control" />
                <span asp-validation-for="DateArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirportDepartureId" class="control-label"></label>
                <select asp-for="AirportDepartureId" class ="form-control" asp-items="ViewBag.AirportDepartureId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AirportArrivalId" class="control-label"></label>
                <select asp-for="AirportArrivalId" class ="form-control" asp-items="ViewBag.AirportArrivalId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Reservation_vols_version2_withEF/Views/Flights/Delete.cshtml
@model Reservation_vols_version2_withEF.Models.Flight

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isopen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isopen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeparture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeparture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportDeparture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportDeparture.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportArrival.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Flightid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Reservation_vols_version2_withEF/Views/Flights/Details.cshtml
@model Reservation_vols_version2_withEF.Models.Flight

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isopen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isopen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateDeparture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateDeparture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateArrival)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateArrival)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportDeparture) ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportDeparture.Airportid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportDeparture) Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportDeparture.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportDeparture) Address
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportDeparture.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportArrival) ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportArrival.Airportid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportArrival) Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportArrival.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AirportArrival) Address
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AirportArrival.Address)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Flightid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Reservation_vols_version2_withEF/Views/Flights/Edit.cshtml
@model Reservation_vols_version2_withEF.Models.Flight

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Flightid" />
            <div class="form-group">
                <label asp-for="DateDeparture" class="control-label"></label>
                <input asp-for="DateDeparture" class="form-control" />
                <span asp-validation-for="DateDeparture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateArrival" class="control-label"></label>
                <input asp-for="DateArrival" class="form-control" />
                <span asp-validation-for="DateArrival" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirportDepartureId" class="control-label"></label>
                <select asp-for="AirportDepartureId" class="form-control" asp-items="ViewBag.AirportDepartureId"></select>
                <span asp-validation-for="AirportDepartureId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AirportArrivalId" class="control-label"></label>
                <select asp-for="AirportArrivalId" class="form-control" asp-items="ViewBag.AirportArrivalId"></select>
                <span asp-validation-for="AirportArrivalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Reservation_vols_version2_withEF/Views/Flights/Index.cshtml
@model Reservation_vols_version2_withEF.ViewModel.FilteredIndexFlightsVM

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Flights" asp-action="Index" method="get">
    <p>
        Aéroport de départ :
        <select asp-for="DepartureAirport" asp-items="Model.Airports">
            <option value="">All</option>
        </select>
        <span style="margin-left:10px;">Aéroport d'arrivée :</span>
        <select asp-for="ArrivalAirport" asp-items="Model.Airports">
            <option value="">All</option>
        </select>
        <input style="margin-left:10px;" type="submit" value="Filter" />
    </p>
</form>

<table class="table sortable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].DateDeparture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].AirportDeparture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].DateArrival)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Flights[0].AirportArrival)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Flights) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateDeparture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AirportDeparture.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateArrival)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AirportArrival.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Flightid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Flightid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Flightid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>